// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dashboard.proto
// Protobuf C++ Version: 5.29.5

#include "dashboard.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr UpdateReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{false},
        errorcode_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateReply::UpdateReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateReplyDefaultTypeInternal() {}
  union {
    UpdateReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateReplyDefaultTypeInternal _UpdateReply_default_instance_;

inline constexpr LossUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : lossvalue_{0},
        iteration_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LossUpdate::LossUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LossUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LossUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LossUpdateDefaultTypeInternal() {}
  union {
    LossUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LossUpdateDefaultTypeInternal _LossUpdate_default_instance_;

inline constexpr ImageData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : image_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        width_{0},
        height_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ImageData::ImageData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ImageDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImageDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImageDataDefaultTypeInternal() {}
  union {
    ImageData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImageDataDefaultTypeInternal _ImageData_default_instance_;

inline constexpr BatchUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : images_{},
        predictions_{},
        groundtruths_{},
        index_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BatchUpdate::BatchUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BatchUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatchUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatchUpdateDefaultTypeInternal() {}
  union {
    BatchUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatchUpdateDefaultTypeInternal _BatchUpdate_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_dashboard_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_dashboard_2eproto = nullptr;
const ::uint32_t
    TableStruct_dashboard_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ImageData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ImageData, _impl_.image_),
        PROTOBUF_FIELD_OFFSET(::ImageData, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::ImageData, _impl_.height_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::BatchUpdate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::BatchUpdate, _impl_.images_),
        PROTOBUF_FIELD_OFFSET(::BatchUpdate, _impl_.predictions_),
        PROTOBUF_FIELD_OFFSET(::BatchUpdate, _impl_.groundtruths_),
        PROTOBUF_FIELD_OFFSET(::BatchUpdate, _impl_.index_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::LossUpdate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::LossUpdate, _impl_.lossvalue_),
        PROTOBUF_FIELD_OFFSET(::LossUpdate, _impl_.iteration_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::UpdateReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::UpdateReply, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::UpdateReply, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::UpdateReply, _impl_.errorcode_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ImageData)},
        {11, -1, -1, sizeof(::BatchUpdate)},
        {23, -1, -1, sizeof(::LossUpdate)},
        {33, -1, -1, sizeof(::UpdateReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ImageData_default_instance_._instance,
    &::_BatchUpdate_default_instance_._instance,
    &::_LossUpdate_default_instance_._instance,
    &::_UpdateReply_default_instance_._instance,
};
const char descriptor_table_protodef_dashboard_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017dashboard.proto\"9\n\tImageData\022\r\n\005image\030"
    "\001 \001(\014\022\r\n\005width\030\002 \001(\005\022\016\n\006height\030\003 \001(\005\"c\n\013"
    "BatchUpdate\022\032\n\006images\030\001 \003(\0132\n.ImageData\022"
    "\023\n\013predictions\030\002 \003(\t\022\024\n\014groundTruths\030\003 \003"
    "(\t\022\r\n\005index\030\004 \001(\005\"2\n\nLossUpdate\022\021\n\tlossV"
    "alue\030\001 \001(\002\022\021\n\titeration\030\002 \001(\005\"A\n\013UpdateR"
    "eply\022\016\n\006status\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\021\n"
    "\terrorCode\030\003 \001(\0052g\n\tDashboard\022-\n\017SendBat"
    "chUpdate\022\014.BatchUpdate\032\014.UpdateReply\022+\n\016"
    "SendLossUpdate\022\013.LossUpdate\032\014.UpdateRepl"
    "yb\006proto3"
};
static ::absl::once_flag descriptor_table_dashboard_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_dashboard_2eproto = {
    false,
    false,
    409,
    descriptor_table_protodef_dashboard_2eproto,
    "dashboard.proto",
    &descriptor_table_dashboard_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_dashboard_2eproto::offsets,
    file_level_enum_descriptors_dashboard_2eproto,
    file_level_service_descriptors_dashboard_2eproto,
};
// ===================================================================

class ImageData::_Internal {
 public:
};

ImageData::ImageData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ImageData)
}
inline PROTOBUF_NDEBUG_INLINE ImageData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ImageData& from_msg)
      : image_(arena, from.image_),
        _cached_size_{0} {}

ImageData::ImageData(
    ::google::protobuf::Arena* arena,
    const ImageData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ImageData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, width_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, width_),
           offsetof(Impl_, height_) -
               offsetof(Impl_, width_) +
               sizeof(Impl_::height_));

  // @@protoc_insertion_point(copy_constructor:ImageData)
}
inline PROTOBUF_NDEBUG_INLINE ImageData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : image_(arena),
        _cached_size_{0} {}

inline void ImageData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, width_),
           0,
           offsetof(Impl_, height_) -
               offsetof(Impl_, width_) +
               sizeof(Impl_::height_));
}
ImageData::~ImageData() {
  // @@protoc_insertion_point(destructor:ImageData)
  SharedDtor(*this);
}
inline void ImageData::SharedDtor(MessageLite& self) {
  ImageData& this_ = static_cast<ImageData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.image_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ImageData::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ImageData(arena);
}
constexpr auto ImageData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ImageData),
                                            alignof(ImageData));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ImageData::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ImageData_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ImageData::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ImageData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ImageData::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ImageData>(), &ImageData::ByteSizeLong,
            &ImageData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ImageData, _impl_._cached_size_),
        false,
    },
    &ImageData::kDescriptorMethods,
    &descriptor_table_dashboard_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ImageData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ImageData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ImageData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes image = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ImageData, _impl_.image_)}},
    // int32 width = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ImageData, _impl_.width_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ImageData, _impl_.width_)}},
    // int32 height = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ImageData, _impl_.height_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ImageData, _impl_.height_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes image = 1;
    {PROTOBUF_FIELD_OFFSET(ImageData, _impl_.image_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // int32 width = 2;
    {PROTOBUF_FIELD_OFFSET(ImageData, _impl_.width_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 height = 3;
    {PROTOBUF_FIELD_OFFSET(ImageData, _impl_.height_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ImageData::Clear() {
// @@protoc_insertion_point(message_clear_start:ImageData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.image_.ClearToEmpty();
  ::memset(&_impl_.width_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.height_) -
      reinterpret_cast<char*>(&_impl_.width_)) + sizeof(_impl_.height_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ImageData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ImageData& this_ = static_cast<const ImageData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ImageData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ImageData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ImageData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes image = 1;
          if (!this_._internal_image().empty()) {
            const std::string& _s = this_._internal_image();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // int32 width = 2;
          if (this_._internal_width() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_width(), target);
          }

          // int32 height = 3;
          if (this_._internal_height() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_height(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ImageData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ImageData::ByteSizeLong(const MessageLite& base) {
          const ImageData& this_ = static_cast<const ImageData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ImageData::ByteSizeLong() const {
          const ImageData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ImageData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes image = 1;
            if (!this_._internal_image().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_image());
            }
            // int32 width = 2;
            if (this_._internal_width() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_width());
            }
            // int32 height = 3;
            if (this_._internal_height() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_height());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ImageData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ImageData*>(&to_msg);
  auto& from = static_cast<const ImageData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ImageData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_image().empty()) {
    _this->_internal_set_image(from._internal_image());
  }
  if (from._internal_width() != 0) {
    _this->_impl_.width_ = from._impl_.width_;
  }
  if (from._internal_height() != 0) {
    _this->_impl_.height_ = from._impl_.height_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ImageData::CopyFrom(const ImageData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ImageData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ImageData::InternalSwap(ImageData* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_, &other->_impl_.image_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ImageData, _impl_.height_)
      + sizeof(ImageData::_impl_.height_)
      - PROTOBUF_FIELD_OFFSET(ImageData, _impl_.width_)>(
          reinterpret_cast<char*>(&_impl_.width_),
          reinterpret_cast<char*>(&other->_impl_.width_));
}

::google::protobuf::Metadata ImageData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BatchUpdate::_Internal {
 public:
};

BatchUpdate::BatchUpdate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BatchUpdate)
}
inline PROTOBUF_NDEBUG_INLINE BatchUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::BatchUpdate& from_msg)
      : images_{visibility, arena, from.images_},
        predictions_{visibility, arena, from.predictions_},
        groundtruths_{visibility, arena, from.groundtruths_},
        _cached_size_{0} {}

BatchUpdate::BatchUpdate(
    ::google::protobuf::Arena* arena,
    const BatchUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BatchUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.index_ = from._impl_.index_;

  // @@protoc_insertion_point(copy_constructor:BatchUpdate)
}
inline PROTOBUF_NDEBUG_INLINE BatchUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : images_{visibility, arena},
        predictions_{visibility, arena},
        groundtruths_{visibility, arena},
        _cached_size_{0} {}

inline void BatchUpdate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.index_ = {};
}
BatchUpdate::~BatchUpdate() {
  // @@protoc_insertion_point(destructor:BatchUpdate)
  SharedDtor(*this);
}
inline void BatchUpdate::SharedDtor(MessageLite& self) {
  BatchUpdate& this_ = static_cast<BatchUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* BatchUpdate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BatchUpdate(arena);
}
constexpr auto BatchUpdate::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.images_) +
          decltype(BatchUpdate::_impl_.images_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.predictions_) +
          decltype(BatchUpdate::_impl_.predictions_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.groundtruths_) +
          decltype(BatchUpdate::_impl_.groundtruths_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(BatchUpdate), alignof(BatchUpdate), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BatchUpdate::PlacementNew_,
                                 sizeof(BatchUpdate),
                                 alignof(BatchUpdate));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BatchUpdate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BatchUpdate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BatchUpdate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BatchUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BatchUpdate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BatchUpdate>(), &BatchUpdate::ByteSizeLong,
            &BatchUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_._cached_size_),
        false,
    },
    &BatchUpdate::kDescriptorMethods,
    &descriptor_table_dashboard_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BatchUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 43, 2> BatchUpdate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::BatchUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 index = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BatchUpdate, _impl_.index_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.index_)}},
    // repeated .ImageData images = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.images_)}},
    // repeated string predictions = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.predictions_)}},
    // repeated string groundTruths = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.groundtruths_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .ImageData images = 1;
    {PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.images_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated string predictions = 2;
    {PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.predictions_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string groundTruths = 3;
    {PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.groundtruths_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // int32 index = 4;
    {PROTOBUF_FIELD_OFFSET(BatchUpdate, _impl_.index_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ImageData>()},
  }}, {{
    "\13\0\13\14\0\0\0\0"
    "BatchUpdate"
    "predictions"
    "groundTruths"
  }},
};

PROTOBUF_NOINLINE void BatchUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:BatchUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.images_.Clear();
  _impl_.predictions_.Clear();
  _impl_.groundtruths_.Clear();
  _impl_.index_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BatchUpdate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BatchUpdate& this_ = static_cast<const BatchUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BatchUpdate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BatchUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:BatchUpdate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .ImageData images = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_images_size());
               i < n; i++) {
            const auto& repfield = this_._internal_images().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated string predictions = 2;
          for (int i = 0, n = this_._internal_predictions_size(); i < n; ++i) {
            const auto& s = this_._internal_predictions().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "BatchUpdate.predictions");
            target = stream->WriteString(2, s, target);
          }

          // repeated string groundTruths = 3;
          for (int i = 0, n = this_._internal_groundtruths_size(); i < n; ++i) {
            const auto& s = this_._internal_groundtruths().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "BatchUpdate.groundTruths");
            target = stream->WriteString(3, s, target);
          }

          // int32 index = 4;
          if (this_._internal_index() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_index(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:BatchUpdate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BatchUpdate::ByteSizeLong(const MessageLite& base) {
          const BatchUpdate& this_ = static_cast<const BatchUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BatchUpdate::ByteSizeLong() const {
          const BatchUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:BatchUpdate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .ImageData images = 1;
            {
              total_size += 1UL * this_._internal_images_size();
              for (const auto& msg : this_._internal_images()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated string predictions = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_predictions().size());
              for (int i = 0, n = this_._internal_predictions().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_predictions().Get(i));
              }
            }
            // repeated string groundTruths = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_groundtruths().size());
              for (int i = 0, n = this_._internal_groundtruths().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_groundtruths().Get(i));
              }
            }
          }
           {
            // int32 index = 4;
            if (this_._internal_index() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_index());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BatchUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BatchUpdate*>(&to_msg);
  auto& from = static_cast<const BatchUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BatchUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_images()->MergeFrom(
      from._internal_images());
  _this->_internal_mutable_predictions()->MergeFrom(from._internal_predictions());
  _this->_internal_mutable_groundtruths()->MergeFrom(from._internal_groundtruths());
  if (from._internal_index() != 0) {
    _this->_impl_.index_ = from._impl_.index_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BatchUpdate::CopyFrom(const BatchUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BatchUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BatchUpdate::InternalSwap(BatchUpdate* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.images_.InternalSwap(&other->_impl_.images_);
  _impl_.predictions_.InternalSwap(&other->_impl_.predictions_);
  _impl_.groundtruths_.InternalSwap(&other->_impl_.groundtruths_);
        swap(_impl_.index_, other->_impl_.index_);
}

::google::protobuf::Metadata BatchUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LossUpdate::_Internal {
 public:
};

LossUpdate::LossUpdate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LossUpdate)
}
LossUpdate::LossUpdate(
    ::google::protobuf::Arena* arena, const LossUpdate& from)
    : LossUpdate(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE LossUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void LossUpdate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, lossvalue_),
           0,
           offsetof(Impl_, iteration_) -
               offsetof(Impl_, lossvalue_) +
               sizeof(Impl_::iteration_));
}
LossUpdate::~LossUpdate() {
  // @@protoc_insertion_point(destructor:LossUpdate)
  SharedDtor(*this);
}
inline void LossUpdate::SharedDtor(MessageLite& self) {
  LossUpdate& this_ = static_cast<LossUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* LossUpdate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LossUpdate(arena);
}
constexpr auto LossUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(LossUpdate),
                                            alignof(LossUpdate));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LossUpdate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LossUpdate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LossUpdate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LossUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LossUpdate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LossUpdate>(), &LossUpdate::ByteSizeLong,
            &LossUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LossUpdate, _impl_._cached_size_),
        false,
    },
    &LossUpdate::kDescriptorMethods,
    &descriptor_table_dashboard_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LossUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> LossUpdate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LossUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 iteration = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(LossUpdate, _impl_.iteration_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LossUpdate, _impl_.iteration_)}},
    // float lossValue = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(LossUpdate, _impl_.lossvalue_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float lossValue = 1;
    {PROTOBUF_FIELD_OFFSET(LossUpdate, _impl_.lossvalue_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // int32 iteration = 2;
    {PROTOBUF_FIELD_OFFSET(LossUpdate, _impl_.iteration_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void LossUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:LossUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.lossvalue_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.iteration_) -
      reinterpret_cast<char*>(&_impl_.lossvalue_)) + sizeof(_impl_.iteration_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LossUpdate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LossUpdate& this_ = static_cast<const LossUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LossUpdate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LossUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:LossUpdate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float lossValue = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_lossvalue()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_lossvalue(), target);
          }

          // int32 iteration = 2;
          if (this_._internal_iteration() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_iteration(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:LossUpdate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LossUpdate::ByteSizeLong(const MessageLite& base) {
          const LossUpdate& this_ = static_cast<const LossUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LossUpdate::ByteSizeLong() const {
          const LossUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:LossUpdate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float lossValue = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_lossvalue()) != 0) {
              total_size += 5;
            }
            // int32 iteration = 2;
            if (this_._internal_iteration() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_iteration());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LossUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LossUpdate*>(&to_msg);
  auto& from = static_cast<const LossUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LossUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_lossvalue()) != 0) {
    _this->_impl_.lossvalue_ = from._impl_.lossvalue_;
  }
  if (from._internal_iteration() != 0) {
    _this->_impl_.iteration_ = from._impl_.iteration_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LossUpdate::CopyFrom(const LossUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LossUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LossUpdate::InternalSwap(LossUpdate* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LossUpdate, _impl_.iteration_)
      + sizeof(LossUpdate::_impl_.iteration_)
      - PROTOBUF_FIELD_OFFSET(LossUpdate, _impl_.lossvalue_)>(
          reinterpret_cast<char*>(&_impl_.lossvalue_),
          reinterpret_cast<char*>(&other->_impl_.lossvalue_));
}

::google::protobuf::Metadata LossUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateReply::_Internal {
 public:
};

UpdateReply::UpdateReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UpdateReply)
}
inline PROTOBUF_NDEBUG_INLINE UpdateReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::UpdateReply& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

UpdateReply::UpdateReply(
    ::google::protobuf::Arena* arena,
    const UpdateReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, status_),
           offsetof(Impl_, errorcode_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::errorcode_));

  // @@protoc_insertion_point(copy_constructor:UpdateReply)
}
inline PROTOBUF_NDEBUG_INLINE UpdateReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void UpdateReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           0,
           offsetof(Impl_, errorcode_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::errorcode_));
}
UpdateReply::~UpdateReply() {
  // @@protoc_insertion_point(destructor:UpdateReply)
  SharedDtor(*this);
}
inline void UpdateReply::SharedDtor(MessageLite& self) {
  UpdateReply& this_ = static_cast<UpdateReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UpdateReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateReply(arena);
}
constexpr auto UpdateReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UpdateReply),
                                            alignof(UpdateReply));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UpdateReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UpdateReply>(), &UpdateReply::ByteSizeLong,
            &UpdateReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_._cached_size_),
        false,
    },
    &UpdateReply::kDescriptorMethods,
    &descriptor_table_dashboard_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 27, 2> UpdateReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::UpdateReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateReply, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.status_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.message_)}},
    // int32 errorCode = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateReply, _impl_.errorcode_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.errorcode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool status = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 errorCode = 3;
    {PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.errorcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\13\0\7\0\0\0\0\0"
    "UpdateReply"
    "message"
  }},
};

PROTOBUF_NOINLINE void UpdateReply::Clear() {
// @@protoc_insertion_point(message_clear_start:UpdateReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  ::memset(&_impl_.status_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.errorcode_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.errorcode_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateReply& this_ = static_cast<const UpdateReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:UpdateReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool status = 1;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_status(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UpdateReply.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 errorCode = 3;
          if (this_._internal_errorcode() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_errorcode(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:UpdateReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateReply::ByteSizeLong(const MessageLite& base) {
          const UpdateReply& this_ = static_cast<const UpdateReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateReply::ByteSizeLong() const {
          const UpdateReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:UpdateReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // bool status = 1;
            if (this_._internal_status() != 0) {
              total_size += 2;
            }
            // int32 errorCode = 3;
            if (this_._internal_errorcode() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_errorcode());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateReply*>(&to_msg);
  auto& from = static_cast<const UpdateReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UpdateReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  if (from._internal_errorcode() != 0) {
    _this->_impl_.errorcode_ = from._impl_.errorcode_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateReply::CopyFrom(const UpdateReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UpdateReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateReply::InternalSwap(UpdateReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.errorcode_)
      + sizeof(UpdateReply::_impl_.errorcode_)
      - PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::google::protobuf::Metadata UpdateReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_dashboard_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
