// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dashboard.proto
#ifndef GRPC_dashboard_2eproto__INCLUDED
#define GRPC_dashboard_2eproto__INCLUDED

#include "dashboard.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class Dashboard final {
 public:
  static constexpr char const* service_full_name() {
    return "Dashboard";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate& request, ::UpdateReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>> AsyncSendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>>(AsyncSendBatchUpdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>> PrepareAsyncSendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>>(PrepareAsyncSendBatchUpdateRaw(context, request, cq));
    }
    virtual ::grpc::Status SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate& request, ::UpdateReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>> AsyncSendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>>(AsyncSendLossUpdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>> PrepareAsyncSendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>>(PrepareAsyncSendLossUpdateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate* request, ::UpdateReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate* request, ::UpdateReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>* AsyncSendBatchUpdateRaw(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>* PrepareAsyncSendBatchUpdateRaw(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>* AsyncSendLossUpdateRaw(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>* PrepareAsyncSendLossUpdateRaw(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate& request, ::UpdateReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>> AsyncSendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>>(AsyncSendBatchUpdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>> PrepareAsyncSendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>>(PrepareAsyncSendBatchUpdateRaw(context, request, cq));
    }
    ::grpc::Status SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate& request, ::UpdateReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>> AsyncSendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>>(AsyncSendLossUpdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>> PrepareAsyncSendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>>(PrepareAsyncSendLossUpdateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate* request, ::UpdateReply* response, std::function<void(::grpc::Status)>) override;
      void SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate* request, ::UpdateReply* response, std::function<void(::grpc::Status)>) override;
      void SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::UpdateReply>* AsyncSendBatchUpdateRaw(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UpdateReply>* PrepareAsyncSendBatchUpdateRaw(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UpdateReply>* AsyncSendLossUpdateRaw(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UpdateReply>* PrepareAsyncSendLossUpdateRaw(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendBatchUpdate_;
    const ::grpc::internal::RpcMethod rpcmethod_SendLossUpdate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendBatchUpdate(::grpc::ServerContext* context, const ::BatchUpdate* request, ::UpdateReply* response);
    virtual ::grpc::Status SendLossUpdate(::grpc::ServerContext* context, const ::LossUpdate* request, ::UpdateReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendBatchUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendBatchUpdate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendBatchUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendBatchUpdate(::grpc::ServerContext* /*context*/, const ::BatchUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendBatchUpdate(::grpc::ServerContext* context, ::BatchUpdate* request, ::grpc::ServerAsyncResponseWriter< ::UpdateReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendLossUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendLossUpdate() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SendLossUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLossUpdate(::grpc::ServerContext* /*context*/, const ::LossUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendLossUpdate(::grpc::ServerContext* context, ::LossUpdate* request, ::grpc::ServerAsyncResponseWriter< ::UpdateReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendBatchUpdate<WithAsyncMethod_SendLossUpdate<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendBatchUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendBatchUpdate() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::BatchUpdate, ::UpdateReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::BatchUpdate* request, ::UpdateReply* response) { return this->SendBatchUpdate(context, request, response); }));}
    void SetMessageAllocatorFor_SendBatchUpdate(
        ::grpc::MessageAllocator< ::BatchUpdate, ::UpdateReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::BatchUpdate, ::UpdateReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendBatchUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendBatchUpdate(::grpc::ServerContext* /*context*/, const ::BatchUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendBatchUpdate(
      ::grpc::CallbackServerContext* /*context*/, const ::BatchUpdate* /*request*/, ::UpdateReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendLossUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendLossUpdate() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::LossUpdate, ::UpdateReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::LossUpdate* request, ::UpdateReply* response) { return this->SendLossUpdate(context, request, response); }));}
    void SetMessageAllocatorFor_SendLossUpdate(
        ::grpc::MessageAllocator< ::LossUpdate, ::UpdateReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::LossUpdate, ::UpdateReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendLossUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLossUpdate(::grpc::ServerContext* /*context*/, const ::LossUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendLossUpdate(
      ::grpc::CallbackServerContext* /*context*/, const ::LossUpdate* /*request*/, ::UpdateReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendBatchUpdate<WithCallbackMethod_SendLossUpdate<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendBatchUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendBatchUpdate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendBatchUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendBatchUpdate(::grpc::ServerContext* /*context*/, const ::BatchUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendLossUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendLossUpdate() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SendLossUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLossUpdate(::grpc::ServerContext* /*context*/, const ::LossUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendBatchUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendBatchUpdate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendBatchUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendBatchUpdate(::grpc::ServerContext* /*context*/, const ::BatchUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendBatchUpdate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendLossUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendLossUpdate() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SendLossUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLossUpdate(::grpc::ServerContext* /*context*/, const ::LossUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendLossUpdate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendBatchUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendBatchUpdate() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendBatchUpdate(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendBatchUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendBatchUpdate(::grpc::ServerContext* /*context*/, const ::BatchUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendBatchUpdate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendLossUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendLossUpdate() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendLossUpdate(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendLossUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendLossUpdate(::grpc::ServerContext* /*context*/, const ::LossUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendLossUpdate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendBatchUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendBatchUpdate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::BatchUpdate, ::UpdateReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::BatchUpdate, ::UpdateReply>* streamer) {
                       return this->StreamedSendBatchUpdate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendBatchUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendBatchUpdate(::grpc::ServerContext* /*context*/, const ::BatchUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendBatchUpdate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::BatchUpdate,::UpdateReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendLossUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendLossUpdate() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::LossUpdate, ::UpdateReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::LossUpdate, ::UpdateReply>* streamer) {
                       return this->StreamedSendLossUpdate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendLossUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendLossUpdate(::grpc::ServerContext* /*context*/, const ::LossUpdate* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendLossUpdate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::LossUpdate,::UpdateReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendBatchUpdate<WithStreamedUnaryMethod_SendLossUpdate<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendBatchUpdate<WithStreamedUnaryMethod_SendLossUpdate<Service > > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_dashboard_2eproto__INCLUDED
