// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dashboard.proto
// Protobuf C++ Version: 5.29.5

#ifndef dashboard_2eproto_2epb_2eh
#define dashboard_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_dashboard_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_dashboard_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_dashboard_2eproto;
class BatchUpdate;
struct BatchUpdateDefaultTypeInternal;
extern BatchUpdateDefaultTypeInternal _BatchUpdate_default_instance_;
class ImageData;
struct ImageDataDefaultTypeInternal;
extern ImageDataDefaultTypeInternal _ImageData_default_instance_;
class LossUpdate;
struct LossUpdateDefaultTypeInternal;
extern LossUpdateDefaultTypeInternal _LossUpdate_default_instance_;
class UpdateReply;
struct UpdateReplyDefaultTypeInternal;
extern UpdateReplyDefaultTypeInternal _UpdateReply_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class UpdateReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:UpdateReply) */ {
 public:
  inline UpdateReply() : UpdateReply(nullptr) {}
  ~UpdateReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UpdateReply* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UpdateReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline UpdateReply(const UpdateReply& from) : UpdateReply(nullptr, from) {}
  inline UpdateReply(UpdateReply&& from) noexcept
      : UpdateReply(nullptr, std::move(from)) {}
  inline UpdateReply& operator=(const UpdateReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateReply& operator=(UpdateReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateReply* internal_default_instance() {
    return reinterpret_cast<const UpdateReply*>(
        &_UpdateReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(UpdateReply& a, UpdateReply& b) { a.Swap(&b); }
  inline void Swap(UpdateReply* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateReply* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UpdateReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UpdateReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UpdateReply& from) { UpdateReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UpdateReply* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "UpdateReply"; }

 protected:
  explicit UpdateReply(::google::protobuf::Arena* arena);
  UpdateReply(::google::protobuf::Arena* arena, const UpdateReply& from);
  UpdateReply(::google::protobuf::Arena* arena, UpdateReply&& from) noexcept
      : UpdateReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kStatusFieldNumber = 1,
    kErrorCodeFieldNumber = 3,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // bool status = 1;
  void clear_status() ;
  bool status() const;
  void set_status(bool value);

  private:
  bool _internal_status() const;
  void _internal_set_status(bool value);

  public:
  // int32 errorCode = 3;
  void clear_errorcode() ;
  ::int32_t errorcode() const;
  void set_errorcode(::int32_t value);

  private:
  ::int32_t _internal_errorcode() const;
  void _internal_set_errorcode(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:UpdateReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      27, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UpdateReply& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    bool status_;
    ::int32_t errorcode_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dashboard_2eproto;
};
// -------------------------------------------------------------------

class LossUpdate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:LossUpdate) */ {
 public:
  inline LossUpdate() : LossUpdate(nullptr) {}
  ~LossUpdate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LossUpdate* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LossUpdate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LossUpdate(
      ::google::protobuf::internal::ConstantInitialized);

  inline LossUpdate(const LossUpdate& from) : LossUpdate(nullptr, from) {}
  inline LossUpdate(LossUpdate&& from) noexcept
      : LossUpdate(nullptr, std::move(from)) {}
  inline LossUpdate& operator=(const LossUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline LossUpdate& operator=(LossUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LossUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const LossUpdate* internal_default_instance() {
    return reinterpret_cast<const LossUpdate*>(
        &_LossUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(LossUpdate& a, LossUpdate& b) { a.Swap(&b); }
  inline void Swap(LossUpdate* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LossUpdate* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LossUpdate* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LossUpdate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LossUpdate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LossUpdate& from) { LossUpdate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LossUpdate* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "LossUpdate"; }

 protected:
  explicit LossUpdate(::google::protobuf::Arena* arena);
  LossUpdate(::google::protobuf::Arena* arena, const LossUpdate& from);
  LossUpdate(::google::protobuf::Arena* arena, LossUpdate&& from) noexcept
      : LossUpdate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLossValueFieldNumber = 1,
    kIterationFieldNumber = 2,
  };
  // float lossValue = 1;
  void clear_lossvalue() ;
  float lossvalue() const;
  void set_lossvalue(float value);

  private:
  float _internal_lossvalue() const;
  void _internal_set_lossvalue(float value);

  public:
  // int32 iteration = 2;
  void clear_iteration() ;
  ::int32_t iteration() const;
  void set_iteration(::int32_t value);

  private:
  ::int32_t _internal_iteration() const;
  void _internal_set_iteration(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:LossUpdate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LossUpdate& from_msg);
    float lossvalue_;
    ::int32_t iteration_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dashboard_2eproto;
};
// -------------------------------------------------------------------

class ImageData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ImageData) */ {
 public:
  inline ImageData() : ImageData(nullptr) {}
  ~ImageData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ImageData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ImageData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImageData(
      ::google::protobuf::internal::ConstantInitialized);

  inline ImageData(const ImageData& from) : ImageData(nullptr, from) {}
  inline ImageData(ImageData&& from) noexcept
      : ImageData(nullptr, std::move(from)) {}
  inline ImageData& operator=(const ImageData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageData& operator=(ImageData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImageData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImageData* internal_default_instance() {
    return reinterpret_cast<const ImageData*>(
        &_ImageData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ImageData& a, ImageData& b) { a.Swap(&b); }
  inline void Swap(ImageData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImageData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ImageData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImageData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ImageData& from) { ImageData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ImageData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ImageData"; }

 protected:
  explicit ImageData(::google::protobuf::Arena* arena);
  ImageData(::google::protobuf::Arena* arena, const ImageData& from);
  ImageData(::google::protobuf::Arena* arena, ImageData&& from) noexcept
      : ImageData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kImageFieldNumber = 1,
    kWidthFieldNumber = 2,
    kHeightFieldNumber = 3,
  };
  // bytes image = 1;
  void clear_image() ;
  const std::string& image() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_image(Arg_&& arg, Args_... args);
  std::string* mutable_image();
  PROTOBUF_NODISCARD std::string* release_image();
  void set_allocated_image(std::string* value);

  private:
  const std::string& _internal_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image(
      const std::string& value);
  std::string* _internal_mutable_image();

  public:
  // int32 width = 2;
  void clear_width() ;
  ::int32_t width() const;
  void set_width(::int32_t value);

  private:
  ::int32_t _internal_width() const;
  void _internal_set_width(::int32_t value);

  public:
  // int32 height = 3;
  void clear_height() ;
  ::int32_t height() const;
  void set_height(::int32_t value);

  private:
  ::int32_t _internal_height() const;
  void _internal_set_height(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ImageData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ImageData& from_msg);
    ::google::protobuf::internal::ArenaStringPtr image_;
    ::int32_t width_;
    ::int32_t height_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dashboard_2eproto;
};
// -------------------------------------------------------------------

class BatchUpdate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:BatchUpdate) */ {
 public:
  inline BatchUpdate() : BatchUpdate(nullptr) {}
  ~BatchUpdate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BatchUpdate* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BatchUpdate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BatchUpdate(
      ::google::protobuf::internal::ConstantInitialized);

  inline BatchUpdate(const BatchUpdate& from) : BatchUpdate(nullptr, from) {}
  inline BatchUpdate(BatchUpdate&& from) noexcept
      : BatchUpdate(nullptr, std::move(from)) {}
  inline BatchUpdate& operator=(const BatchUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatchUpdate& operator=(BatchUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatchUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const BatchUpdate* internal_default_instance() {
    return reinterpret_cast<const BatchUpdate*>(
        &_BatchUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BatchUpdate& a, BatchUpdate& b) { a.Swap(&b); }
  inline void Swap(BatchUpdate* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatchUpdate* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatchUpdate* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BatchUpdate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BatchUpdate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BatchUpdate& from) { BatchUpdate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BatchUpdate* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "BatchUpdate"; }

 protected:
  explicit BatchUpdate(::google::protobuf::Arena* arena);
  BatchUpdate(::google::protobuf::Arena* arena, const BatchUpdate& from);
  BatchUpdate(::google::protobuf::Arena* arena, BatchUpdate&& from) noexcept
      : BatchUpdate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kImagesFieldNumber = 1,
    kPredictionsFieldNumber = 2,
    kGroundTruthsFieldNumber = 3,
    kIndexFieldNumber = 4,
  };
  // repeated .ImageData images = 1;
  int images_size() const;
  private:
  int _internal_images_size() const;

  public:
  void clear_images() ;
  ::ImageData* mutable_images(int index);
  ::google::protobuf::RepeatedPtrField<::ImageData>* mutable_images();

  private:
  const ::google::protobuf::RepeatedPtrField<::ImageData>& _internal_images() const;
  ::google::protobuf::RepeatedPtrField<::ImageData>* _internal_mutable_images();
  public:
  const ::ImageData& images(int index) const;
  ::ImageData* add_images();
  const ::google::protobuf::RepeatedPtrField<::ImageData>& images() const;
  // repeated string predictions = 2;
  int predictions_size() const;
  private:
  int _internal_predictions_size() const;

  public:
  void clear_predictions() ;
  const std::string& predictions(int index) const;
  std::string* mutable_predictions(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_predictions(int index, Arg_&& value, Args_... args);
  std::string* add_predictions();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_predictions(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& predictions() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_predictions();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_predictions() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_predictions();

  public:
  // repeated string groundTruths = 3;
  int groundtruths_size() const;
  private:
  int _internal_groundtruths_size() const;

  public:
  void clear_groundtruths() ;
  const std::string& groundtruths(int index) const;
  std::string* mutable_groundtruths(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_groundtruths(int index, Arg_&& value, Args_... args);
  std::string* add_groundtruths();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_groundtruths(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& groundtruths() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_groundtruths();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_groundtruths() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_groundtruths();

  public:
  // int32 index = 4;
  void clear_index() ;
  ::int32_t index() const;
  void set_index(::int32_t value);

  private:
  ::int32_t _internal_index() const;
  void _internal_set_index(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:BatchUpdate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 1,
      43, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BatchUpdate& from_msg);
    ::google::protobuf::RepeatedPtrField< ::ImageData > images_;
    ::google::protobuf::RepeatedPtrField<std::string> predictions_;
    ::google::protobuf::RepeatedPtrField<std::string> groundtruths_;
    ::int32_t index_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dashboard_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ImageData

// bytes image = 1;
inline void ImageData::clear_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_.ClearToEmpty();
}
inline const std::string& ImageData::image() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ImageData.image)
  return _internal_image();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ImageData::set_image(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ImageData.image)
}
inline std::string* ImageData::mutable_image() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_image();
  // @@protoc_insertion_point(field_mutable:ImageData.image)
  return _s;
}
inline const std::string& ImageData::_internal_image() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_.Get();
}
inline void ImageData::_internal_set_image(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_.Set(value, GetArena());
}
inline std::string* ImageData::_internal_mutable_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.image_.Mutable( GetArena());
}
inline std::string* ImageData::release_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ImageData.image)
  return _impl_.image_.Release();
}
inline void ImageData::set_allocated_image(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.image_.IsDefault()) {
    _impl_.image_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ImageData.image)
}

// int32 width = 2;
inline void ImageData::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0;
}
inline ::int32_t ImageData::width() const {
  // @@protoc_insertion_point(field_get:ImageData.width)
  return _internal_width();
}
inline void ImageData::set_width(::int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:ImageData.width)
}
inline ::int32_t ImageData::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void ImageData::_internal_set_width(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// int32 height = 3;
inline void ImageData::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0;
}
inline ::int32_t ImageData::height() const {
  // @@protoc_insertion_point(field_get:ImageData.height)
  return _internal_height();
}
inline void ImageData::set_height(::int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:ImageData.height)
}
inline ::int32_t ImageData::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void ImageData::_internal_set_height(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// -------------------------------------------------------------------

// BatchUpdate

// repeated .ImageData images = 1;
inline int BatchUpdate::_internal_images_size() const {
  return _internal_images().size();
}
inline int BatchUpdate::images_size() const {
  return _internal_images_size();
}
inline void BatchUpdate::clear_images() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.images_.Clear();
}
inline ::ImageData* BatchUpdate::mutable_images(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:BatchUpdate.images)
  return _internal_mutable_images()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::ImageData>* BatchUpdate::mutable_images()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:BatchUpdate.images)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_images();
}
inline const ::ImageData& BatchUpdate::images(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:BatchUpdate.images)
  return _internal_images().Get(index);
}
inline ::ImageData* BatchUpdate::add_images() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::ImageData* _add = _internal_mutable_images()->Add();
  // @@protoc_insertion_point(field_add:BatchUpdate.images)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::ImageData>& BatchUpdate::images() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:BatchUpdate.images)
  return _internal_images();
}
inline const ::google::protobuf::RepeatedPtrField<::ImageData>&
BatchUpdate::_internal_images() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.images_;
}
inline ::google::protobuf::RepeatedPtrField<::ImageData>*
BatchUpdate::_internal_mutable_images() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.images_;
}

// repeated string predictions = 2;
inline int BatchUpdate::_internal_predictions_size() const {
  return _internal_predictions().size();
}
inline int BatchUpdate::predictions_size() const {
  return _internal_predictions_size();
}
inline void BatchUpdate::clear_predictions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.predictions_.Clear();
}
inline std::string* BatchUpdate::add_predictions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_predictions()->Add();
  // @@protoc_insertion_point(field_add_mutable:BatchUpdate.predictions)
  return _s;
}
inline const std::string& BatchUpdate::predictions(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:BatchUpdate.predictions)
  return _internal_predictions().Get(index);
}
inline std::string* BatchUpdate::mutable_predictions(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:BatchUpdate.predictions)
  return _internal_mutable_predictions()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void BatchUpdate::set_predictions(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_predictions()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:BatchUpdate.predictions)
}
template <typename Arg_, typename... Args_>
inline void BatchUpdate::add_predictions(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_predictions(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:BatchUpdate.predictions)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
BatchUpdate::predictions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:BatchUpdate.predictions)
  return _internal_predictions();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
BatchUpdate::mutable_predictions() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:BatchUpdate.predictions)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_predictions();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
BatchUpdate::_internal_predictions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.predictions_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
BatchUpdate::_internal_mutable_predictions() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.predictions_;
}

// repeated string groundTruths = 3;
inline int BatchUpdate::_internal_groundtruths_size() const {
  return _internal_groundtruths().size();
}
inline int BatchUpdate::groundtruths_size() const {
  return _internal_groundtruths_size();
}
inline void BatchUpdate::clear_groundtruths() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.groundtruths_.Clear();
}
inline std::string* BatchUpdate::add_groundtruths() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_groundtruths()->Add();
  // @@protoc_insertion_point(field_add_mutable:BatchUpdate.groundTruths)
  return _s;
}
inline const std::string& BatchUpdate::groundtruths(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:BatchUpdate.groundTruths)
  return _internal_groundtruths().Get(index);
}
inline std::string* BatchUpdate::mutable_groundtruths(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:BatchUpdate.groundTruths)
  return _internal_mutable_groundtruths()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void BatchUpdate::set_groundtruths(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_groundtruths()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:BatchUpdate.groundTruths)
}
template <typename Arg_, typename... Args_>
inline void BatchUpdate::add_groundtruths(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_groundtruths(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:BatchUpdate.groundTruths)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
BatchUpdate::groundtruths() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:BatchUpdate.groundTruths)
  return _internal_groundtruths();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
BatchUpdate::mutable_groundtruths() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:BatchUpdate.groundTruths)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_groundtruths();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
BatchUpdate::_internal_groundtruths() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.groundtruths_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
BatchUpdate::_internal_mutable_groundtruths() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.groundtruths_;
}

// int32 index = 4;
inline void BatchUpdate::clear_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.index_ = 0;
}
inline ::int32_t BatchUpdate::index() const {
  // @@protoc_insertion_point(field_get:BatchUpdate.index)
  return _internal_index();
}
inline void BatchUpdate::set_index(::int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:BatchUpdate.index)
}
inline ::int32_t BatchUpdate::_internal_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.index_;
}
inline void BatchUpdate::_internal_set_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.index_ = value;
}

// -------------------------------------------------------------------

// LossUpdate

// float lossValue = 1;
inline void LossUpdate::clear_lossvalue() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lossvalue_ = 0;
}
inline float LossUpdate::lossvalue() const {
  // @@protoc_insertion_point(field_get:LossUpdate.lossValue)
  return _internal_lossvalue();
}
inline void LossUpdate::set_lossvalue(float value) {
  _internal_set_lossvalue(value);
  // @@protoc_insertion_point(field_set:LossUpdate.lossValue)
}
inline float LossUpdate::_internal_lossvalue() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lossvalue_;
}
inline void LossUpdate::_internal_set_lossvalue(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lossvalue_ = value;
}

// int32 iteration = 2;
inline void LossUpdate::clear_iteration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iteration_ = 0;
}
inline ::int32_t LossUpdate::iteration() const {
  // @@protoc_insertion_point(field_get:LossUpdate.iteration)
  return _internal_iteration();
}
inline void LossUpdate::set_iteration(::int32_t value) {
  _internal_set_iteration(value);
  // @@protoc_insertion_point(field_set:LossUpdate.iteration)
}
inline ::int32_t LossUpdate::_internal_iteration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iteration_;
}
inline void LossUpdate::_internal_set_iteration(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iteration_ = value;
}

// -------------------------------------------------------------------

// UpdateReply

// bool status = 1;
inline void UpdateReply::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = false;
}
inline bool UpdateReply::status() const {
  // @@protoc_insertion_point(field_get:UpdateReply.status)
  return _internal_status();
}
inline void UpdateReply::set_status(bool value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:UpdateReply.status)
}
inline bool UpdateReply::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void UpdateReply::_internal_set_status(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string message = 2;
inline void UpdateReply::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& UpdateReply::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:UpdateReply.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UpdateReply::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:UpdateReply.message)
}
inline std::string* UpdateReply::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:UpdateReply.message)
  return _s;
}
inline const std::string& UpdateReply::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void UpdateReply::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* UpdateReply::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* UpdateReply::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:UpdateReply.message)
  return _impl_.message_.Release();
}
inline void UpdateReply::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:UpdateReply.message)
}

// int32 errorCode = 3;
inline void UpdateReply::clear_errorcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errorcode_ = 0;
}
inline ::int32_t UpdateReply::errorcode() const {
  // @@protoc_insertion_point(field_get:UpdateReply.errorCode)
  return _internal_errorcode();
}
inline void UpdateReply::set_errorcode(::int32_t value) {
  _internal_set_errorcode(value);
  // @@protoc_insertion_point(field_set:UpdateReply.errorCode)
}
inline ::int32_t UpdateReply::_internal_errorcode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errorcode_;
}
inline void UpdateReply::_internal_set_errorcode(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errorcode_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // dashboard_2eproto_2epb_2eh
