// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dashboard.proto

#include "dashboard.pb.h"
#include "dashboard.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Dashboard_method_names[] = {
  "/Dashboard/SendBatchUpdate",
  "/Dashboard/SendLossUpdate",
};

std::unique_ptr< Dashboard::Stub> Dashboard::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Dashboard::Stub> stub(new Dashboard::Stub(channel, options));
  return stub;
}

Dashboard::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendBatchUpdate_(Dashboard_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendLossUpdate_(Dashboard_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Dashboard::Stub::SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate& request, ::UpdateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BatchUpdate, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendBatchUpdate_, context, request, response);
}

void Dashboard::Stub::async::SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate* request, ::UpdateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BatchUpdate, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBatchUpdate_, context, request, response, std::move(f));
}

void Dashboard::Stub::async::SendBatchUpdate(::grpc::ClientContext* context, const ::BatchUpdate* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendBatchUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::UpdateReply>* Dashboard::Stub::PrepareAsyncSendBatchUpdateRaw(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::UpdateReply, ::BatchUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendBatchUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::UpdateReply>* Dashboard::Stub::AsyncSendBatchUpdateRaw(::grpc::ClientContext* context, const ::BatchUpdate& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendBatchUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Dashboard::Stub::SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate& request, ::UpdateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::LossUpdate, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendLossUpdate_, context, request, response);
}

void Dashboard::Stub::async::SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate* request, ::UpdateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::LossUpdate, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendLossUpdate_, context, request, response, std::move(f));
}

void Dashboard::Stub::async::SendLossUpdate(::grpc::ClientContext* context, const ::LossUpdate* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendLossUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::UpdateReply>* Dashboard::Stub::PrepareAsyncSendLossUpdateRaw(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::UpdateReply, ::LossUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendLossUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::UpdateReply>* Dashboard::Stub::AsyncSendLossUpdateRaw(::grpc::ClientContext* context, const ::LossUpdate& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendLossUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

Dashboard::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Dashboard_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Dashboard::Service, ::BatchUpdate, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Dashboard::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BatchUpdate* req,
             ::UpdateReply* resp) {
               return service->SendBatchUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Dashboard_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Dashboard::Service, ::LossUpdate, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Dashboard::Service* service,
             ::grpc::ServerContext* ctx,
             const ::LossUpdate* req,
             ::UpdateReply* resp) {
               return service->SendLossUpdate(ctx, req, resp);
             }, this)));
}

Dashboard::Service::~Service() {
}

::grpc::Status Dashboard::Service::SendBatchUpdate(::grpc::ServerContext* context, const ::BatchUpdate* request, ::UpdateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Dashboard::Service::SendLossUpdate(::grpc::ServerContext* context, const ::LossUpdate* request, ::UpdateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


