// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: training.proto

#include "training.pb.h"
#include "training.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Training_method_names[] = {
  "/Training/TrainingStatusUpdate",
  "/Training/TrainingMetricsUpdate",
};

std::unique_ptr< Training::Stub> Training::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Training::Stub> stub(new Training::Stub(channel, options));
  return stub;
}

Training::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_TrainingStatusUpdate_(Training_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TrainingMetricsUpdate_(Training_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Training::Stub::TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus& request, ::UpdateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TrainingStatus, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TrainingStatusUpdate_, context, request, response);
}

void Training::Stub::async::TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus* request, ::UpdateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TrainingStatus, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TrainingStatusUpdate_, context, request, response, std::move(f));
}

void Training::Stub::async::TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TrainingStatusUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::UpdateReply>* Training::Stub::PrepareAsyncTrainingStatusUpdateRaw(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::UpdateReply, ::TrainingStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TrainingStatusUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::UpdateReply>* Training::Stub::AsyncTrainingStatusUpdateRaw(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTrainingStatusUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Training::Stub::TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::UpdateReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TrainingMetrics, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TrainingMetricsUpdate_, context, request, response);
}

void Training::Stub::async::TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics* request, ::UpdateReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TrainingMetrics, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TrainingMetricsUpdate_, context, request, response, std::move(f));
}

void Training::Stub::async::TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TrainingMetricsUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::UpdateReply>* Training::Stub::PrepareAsyncTrainingMetricsUpdateRaw(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::UpdateReply, ::TrainingMetrics, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TrainingMetricsUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::UpdateReply>* Training::Stub::AsyncTrainingMetricsUpdateRaw(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTrainingMetricsUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

Training::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Training_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Training::Service, ::TrainingStatus, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Training::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TrainingStatus* req,
             ::UpdateReply* resp) {
               return service->TrainingStatusUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Training_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Training::Service, ::TrainingMetrics, ::UpdateReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Training::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TrainingMetrics* req,
             ::UpdateReply* resp) {
               return service->TrainingMetricsUpdate(ctx, req, resp);
             }, this)));
}

Training::Service::~Service() {
}

::grpc::Status Training::Service::TrainingStatusUpdate(::grpc::ServerContext* context, const ::TrainingStatus* request, ::UpdateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Training::Service::TrainingMetricsUpdate(::grpc::ServerContext* context, const ::TrainingMetrics* request, ::UpdateReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


