// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: training.proto
#ifndef GRPC_training_2eproto__INCLUDED
#define GRPC_training_2eproto__INCLUDED

#include "training.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class Training final {
 public:
  static constexpr char const* service_full_name() {
    return "Training";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus& request, ::UpdateReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>> AsyncTrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>>(AsyncTrainingStatusUpdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>> PrepareAsyncTrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>>(PrepareAsyncTrainingStatusUpdateRaw(context, request, cq));
    }
    virtual ::grpc::Status TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::UpdateReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>> AsyncTrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>>(AsyncTrainingMetricsUpdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>> PrepareAsyncTrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>>(PrepareAsyncTrainingMetricsUpdateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus* request, ::UpdateReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics* request, ::UpdateReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>* AsyncTrainingStatusUpdateRaw(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>* PrepareAsyncTrainingStatusUpdateRaw(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>* AsyncTrainingMetricsUpdateRaw(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UpdateReply>* PrepareAsyncTrainingMetricsUpdateRaw(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus& request, ::UpdateReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>> AsyncTrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>>(AsyncTrainingStatusUpdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>> PrepareAsyncTrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>>(PrepareAsyncTrainingStatusUpdateRaw(context, request, cq));
    }
    ::grpc::Status TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::UpdateReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>> AsyncTrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>>(AsyncTrainingMetricsUpdateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>> PrepareAsyncTrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UpdateReply>>(PrepareAsyncTrainingMetricsUpdateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus* request, ::UpdateReply* response, std::function<void(::grpc::Status)>) override;
      void TrainingStatusUpdate(::grpc::ClientContext* context, const ::TrainingStatus* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics* request, ::UpdateReply* response, std::function<void(::grpc::Status)>) override;
      void TrainingMetricsUpdate(::grpc::ClientContext* context, const ::TrainingMetrics* request, ::UpdateReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::UpdateReply>* AsyncTrainingStatusUpdateRaw(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UpdateReply>* PrepareAsyncTrainingStatusUpdateRaw(::grpc::ClientContext* context, const ::TrainingStatus& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UpdateReply>* AsyncTrainingMetricsUpdateRaw(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::UpdateReply>* PrepareAsyncTrainingMetricsUpdateRaw(::grpc::ClientContext* context, const ::TrainingMetrics& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TrainingStatusUpdate_;
    const ::grpc::internal::RpcMethod rpcmethod_TrainingMetricsUpdate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status TrainingStatusUpdate(::grpc::ServerContext* context, const ::TrainingStatus* request, ::UpdateReply* response);
    virtual ::grpc::Status TrainingMetricsUpdate(::grpc::ServerContext* context, const ::TrainingMetrics* request, ::UpdateReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_TrainingStatusUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TrainingStatusUpdate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TrainingStatusUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingStatusUpdate(::grpc::ServerContext* /*context*/, const ::TrainingStatus* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTrainingStatusUpdate(::grpc::ServerContext* context, ::TrainingStatus* request, ::grpc::ServerAsyncResponseWriter< ::UpdateReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TrainingMetricsUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TrainingMetricsUpdate() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_TrainingMetricsUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingMetricsUpdate(::grpc::ServerContext* /*context*/, const ::TrainingMetrics* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTrainingMetricsUpdate(::grpc::ServerContext* context, ::TrainingMetrics* request, ::grpc::ServerAsyncResponseWriter< ::UpdateReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TrainingStatusUpdate<WithAsyncMethod_TrainingMetricsUpdate<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_TrainingStatusUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TrainingStatusUpdate() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::TrainingStatus, ::UpdateReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TrainingStatus* request, ::UpdateReply* response) { return this->TrainingStatusUpdate(context, request, response); }));}
    void SetMessageAllocatorFor_TrainingStatusUpdate(
        ::grpc::MessageAllocator< ::TrainingStatus, ::UpdateReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::TrainingStatus, ::UpdateReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TrainingStatusUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingStatusUpdate(::grpc::ServerContext* /*context*/, const ::TrainingStatus* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TrainingStatusUpdate(
      ::grpc::CallbackServerContext* /*context*/, const ::TrainingStatus* /*request*/, ::UpdateReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_TrainingMetricsUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TrainingMetricsUpdate() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::TrainingMetrics, ::UpdateReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TrainingMetrics* request, ::UpdateReply* response) { return this->TrainingMetricsUpdate(context, request, response); }));}
    void SetMessageAllocatorFor_TrainingMetricsUpdate(
        ::grpc::MessageAllocator< ::TrainingMetrics, ::UpdateReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::TrainingMetrics, ::UpdateReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TrainingMetricsUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingMetricsUpdate(::grpc::ServerContext* /*context*/, const ::TrainingMetrics* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TrainingMetricsUpdate(
      ::grpc::CallbackServerContext* /*context*/, const ::TrainingMetrics* /*request*/, ::UpdateReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_TrainingStatusUpdate<WithCallbackMethod_TrainingMetricsUpdate<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_TrainingStatusUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TrainingStatusUpdate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TrainingStatusUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingStatusUpdate(::grpc::ServerContext* /*context*/, const ::TrainingStatus* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TrainingMetricsUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TrainingMetricsUpdate() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_TrainingMetricsUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingMetricsUpdate(::grpc::ServerContext* /*context*/, const ::TrainingMetrics* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_TrainingStatusUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TrainingStatusUpdate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_TrainingStatusUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingStatusUpdate(::grpc::ServerContext* /*context*/, const ::TrainingStatus* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTrainingStatusUpdate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_TrainingMetricsUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TrainingMetricsUpdate() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_TrainingMetricsUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingMetricsUpdate(::grpc::ServerContext* /*context*/, const ::TrainingMetrics* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTrainingMetricsUpdate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TrainingStatusUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TrainingStatusUpdate() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TrainingStatusUpdate(context, request, response); }));
    }
    ~WithRawCallbackMethod_TrainingStatusUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingStatusUpdate(::grpc::ServerContext* /*context*/, const ::TrainingStatus* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TrainingStatusUpdate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TrainingMetricsUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TrainingMetricsUpdate() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TrainingMetricsUpdate(context, request, response); }));
    }
    ~WithRawCallbackMethod_TrainingMetricsUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TrainingMetricsUpdate(::grpc::ServerContext* /*context*/, const ::TrainingMetrics* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TrainingMetricsUpdate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TrainingStatusUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TrainingStatusUpdate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::TrainingStatus, ::UpdateReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::TrainingStatus, ::UpdateReply>* streamer) {
                       return this->StreamedTrainingStatusUpdate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TrainingStatusUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TrainingStatusUpdate(::grpc::ServerContext* /*context*/, const ::TrainingStatus* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTrainingStatusUpdate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TrainingStatus,::UpdateReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TrainingMetricsUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TrainingMetricsUpdate() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::TrainingMetrics, ::UpdateReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::TrainingMetrics, ::UpdateReply>* streamer) {
                       return this->StreamedTrainingMetricsUpdate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TrainingMetricsUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TrainingMetricsUpdate(::grpc::ServerContext* /*context*/, const ::TrainingMetrics* /*request*/, ::UpdateReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTrainingMetricsUpdate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TrainingMetrics,::UpdateReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TrainingStatusUpdate<WithStreamedUnaryMethod_TrainingMetricsUpdate<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_TrainingStatusUpdate<WithStreamedUnaryMethod_TrainingMetricsUpdate<Service > > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_training_2eproto__INCLUDED
