// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: training.proto
// Protobuf C++ Version: 5.29.5

#ifndef training_2eproto_2epb_2eh
#define training_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_training_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_training_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_training_2eproto;
class TrainingMetrics;
struct TrainingMetricsDefaultTypeInternal;
extern TrainingMetricsDefaultTypeInternal _TrainingMetrics_default_instance_;
class TrainingStatus;
struct TrainingStatusDefaultTypeInternal;
extern TrainingStatusDefaultTypeInternal _TrainingStatus_default_instance_;
class UpdateReply;
struct UpdateReplyDefaultTypeInternal;
extern UpdateReplyDefaultTypeInternal _UpdateReply_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class UpdateReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:UpdateReply) */ {
 public:
  inline UpdateReply() : UpdateReply(nullptr) {}
  ~UpdateReply() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UpdateReply* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UpdateReply));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UpdateReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline UpdateReply(const UpdateReply& from) : UpdateReply(nullptr, from) {}
  inline UpdateReply(UpdateReply&& from) noexcept
      : UpdateReply(nullptr, std::move(from)) {}
  inline UpdateReply& operator=(const UpdateReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateReply& operator=(UpdateReply&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateReply* internal_default_instance() {
    return reinterpret_cast<const UpdateReply*>(
        &_UpdateReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(UpdateReply& a, UpdateReply& b) { a.Swap(&b); }
  inline void Swap(UpdateReply* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateReply* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UpdateReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UpdateReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UpdateReply& from) { UpdateReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UpdateReply* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "UpdateReply"; }

 protected:
  explicit UpdateReply(::google::protobuf::Arena* arena);
  UpdateReply(::google::protobuf::Arena* arena, const UpdateReply& from);
  UpdateReply(::google::protobuf::Arena* arena, UpdateReply&& from) noexcept
      : UpdateReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 2,
    kStatusFieldNumber = 1,
    kErrorCodeFieldNumber = 3,
  };
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // bool status = 1;
  void clear_status() ;
  bool status() const;
  void set_status(bool value);

  private:
  bool _internal_status() const;
  void _internal_set_status(bool value);

  public:
  // int32 errorCode = 3;
  void clear_errorcode() ;
  ::int32_t errorcode() const;
  void set_errorcode(::int32_t value);

  private:
  ::int32_t _internal_errorcode() const;
  void _internal_set_errorcode(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:UpdateReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      27, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UpdateReply& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    bool status_;
    ::int32_t errorcode_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_training_2eproto;
};
// -------------------------------------------------------------------

class TrainingStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TrainingStatus) */ {
 public:
  inline TrainingStatus() : TrainingStatus(nullptr) {}
  ~TrainingStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrainingStatus* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrainingStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrainingStatus(
      ::google::protobuf::internal::ConstantInitialized);

  inline TrainingStatus(const TrainingStatus& from) : TrainingStatus(nullptr, from) {}
  inline TrainingStatus(TrainingStatus&& from) noexcept
      : TrainingStatus(nullptr, std::move(from)) {}
  inline TrainingStatus& operator=(const TrainingStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainingStatus& operator=(TrainingStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrainingStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrainingStatus* internal_default_instance() {
    return reinterpret_cast<const TrainingStatus*>(
        &_TrainingStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TrainingStatus& a, TrainingStatus& b) { a.Swap(&b); }
  inline void Swap(TrainingStatus* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainingStatus* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrainingStatus* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrainingStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrainingStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrainingStatus& from) { TrainingStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrainingStatus* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TrainingStatus"; }

 protected:
  explicit TrainingStatus(::google::protobuf::Arena* arena);
  TrainingStatus(::google::protobuf::Arena* arena, const TrainingStatus& from);
  TrainingStatus(::google::protobuf::Arena* arena, TrainingStatus&& from) noexcept
      : TrainingStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusMessageFieldNumber = 2,
    kIsTrainingFieldNumber = 1,
  };
  // string statusMessage = 2;
  void clear_statusmessage() ;
  const std::string& statusmessage() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_statusmessage(Arg_&& arg, Args_... args);
  std::string* mutable_statusmessage();
  PROTOBUF_NODISCARD std::string* release_statusmessage();
  void set_allocated_statusmessage(std::string* value);

  private:
  const std::string& _internal_statusmessage() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_statusmessage(
      const std::string& value);
  std::string* _internal_mutable_statusmessage();

  public:
  // bool isTraining = 1;
  void clear_istraining() ;
  bool istraining() const;
  void set_istraining(bool value);

  private:
  bool _internal_istraining() const;
  void _internal_set_istraining(bool value);

  public:
  // @@protoc_insertion_point(class_scope:TrainingStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      36, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TrainingStatus& from_msg);
    ::google::protobuf::internal::ArenaStringPtr statusmessage_;
    bool istraining_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_training_2eproto;
};
// -------------------------------------------------------------------

class TrainingMetrics final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TrainingMetrics) */ {
 public:
  inline TrainingMetrics() : TrainingMetrics(nullptr) {}
  ~TrainingMetrics() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrainingMetrics* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrainingMetrics));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrainingMetrics(
      ::google::protobuf::internal::ConstantInitialized);

  inline TrainingMetrics(const TrainingMetrics& from) : TrainingMetrics(nullptr, from) {}
  inline TrainingMetrics(TrainingMetrics&& from) noexcept
      : TrainingMetrics(nullptr, std::move(from)) {}
  inline TrainingMetrics& operator=(const TrainingMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrainingMetrics& operator=(TrainingMetrics&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrainingMetrics& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrainingMetrics* internal_default_instance() {
    return reinterpret_cast<const TrainingMetrics*>(
        &_TrainingMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(TrainingMetrics& a, TrainingMetrics& b) { a.Swap(&b); }
  inline void Swap(TrainingMetrics* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrainingMetrics* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrainingMetrics* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrainingMetrics>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrainingMetrics& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrainingMetrics& from) { TrainingMetrics::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrainingMetrics* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TrainingMetrics"; }

 protected:
  explicit TrainingMetrics(::google::protobuf::Arena* arena);
  TrainingMetrics(::google::protobuf::Arena* arena, const TrainingMetrics& from);
  TrainingMetrics(::google::protobuf::Arena* arena, TrainingMetrics&& from) noexcept
      : TrainingMetrics(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCurrentLossFieldNumber = 1,
    kCurrentIterationFieldNumber = 2,
  };
  // float currentLoss = 1;
  void clear_currentloss() ;
  float currentloss() const;
  void set_currentloss(float value);

  private:
  float _internal_currentloss() const;
  void _internal_set_currentloss(float value);

  public:
  // float currentIteration = 2;
  void clear_currentiteration() ;
  float currentiteration() const;
  void set_currentiteration(float value);

  private:
  float _internal_currentiteration() const;
  void _internal_set_currentiteration(float value);

  public:
  // @@protoc_insertion_point(class_scope:TrainingMetrics)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TrainingMetrics& from_msg);
    float currentloss_;
    float currentiteration_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_training_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TrainingStatus

// bool isTraining = 1;
inline void TrainingStatus::clear_istraining() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.istraining_ = false;
}
inline bool TrainingStatus::istraining() const {
  // @@protoc_insertion_point(field_get:TrainingStatus.isTraining)
  return _internal_istraining();
}
inline void TrainingStatus::set_istraining(bool value) {
  _internal_set_istraining(value);
  // @@protoc_insertion_point(field_set:TrainingStatus.isTraining)
}
inline bool TrainingStatus::_internal_istraining() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.istraining_;
}
inline void TrainingStatus::_internal_set_istraining(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.istraining_ = value;
}

// string statusMessage = 2;
inline void TrainingStatus::clear_statusmessage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.statusmessage_.ClearToEmpty();
}
inline const std::string& TrainingStatus::statusmessage() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TrainingStatus.statusMessage)
  return _internal_statusmessage();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TrainingStatus::set_statusmessage(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.statusmessage_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:TrainingStatus.statusMessage)
}
inline std::string* TrainingStatus::mutable_statusmessage() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_statusmessage();
  // @@protoc_insertion_point(field_mutable:TrainingStatus.statusMessage)
  return _s;
}
inline const std::string& TrainingStatus::_internal_statusmessage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.statusmessage_.Get();
}
inline void TrainingStatus::_internal_set_statusmessage(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.statusmessage_.Set(value, GetArena());
}
inline std::string* TrainingStatus::_internal_mutable_statusmessage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.statusmessage_.Mutable( GetArena());
}
inline std::string* TrainingStatus::release_statusmessage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:TrainingStatus.statusMessage)
  return _impl_.statusmessage_.Release();
}
inline void TrainingStatus::set_allocated_statusmessage(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.statusmessage_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.statusmessage_.IsDefault()) {
    _impl_.statusmessage_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:TrainingStatus.statusMessage)
}

// -------------------------------------------------------------------

// TrainingMetrics

// float currentLoss = 1;
inline void TrainingMetrics::clear_currentloss() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currentloss_ = 0;
}
inline float TrainingMetrics::currentloss() const {
  // @@protoc_insertion_point(field_get:TrainingMetrics.currentLoss)
  return _internal_currentloss();
}
inline void TrainingMetrics::set_currentloss(float value) {
  _internal_set_currentloss(value);
  // @@protoc_insertion_point(field_set:TrainingMetrics.currentLoss)
}
inline float TrainingMetrics::_internal_currentloss() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.currentloss_;
}
inline void TrainingMetrics::_internal_set_currentloss(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currentloss_ = value;
}

// float currentIteration = 2;
inline void TrainingMetrics::clear_currentiteration() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currentiteration_ = 0;
}
inline float TrainingMetrics::currentiteration() const {
  // @@protoc_insertion_point(field_get:TrainingMetrics.currentIteration)
  return _internal_currentiteration();
}
inline void TrainingMetrics::set_currentiteration(float value) {
  _internal_set_currentiteration(value);
  // @@protoc_insertion_point(field_set:TrainingMetrics.currentIteration)
}
inline float TrainingMetrics::_internal_currentiteration() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.currentiteration_;
}
inline void TrainingMetrics::_internal_set_currentiteration(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.currentiteration_ = value;
}

// -------------------------------------------------------------------

// UpdateReply

// bool status = 1;
inline void UpdateReply::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = false;
}
inline bool UpdateReply::status() const {
  // @@protoc_insertion_point(field_get:UpdateReply.status)
  return _internal_status();
}
inline void UpdateReply::set_status(bool value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:UpdateReply.status)
}
inline bool UpdateReply::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void UpdateReply::_internal_set_status(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string message = 2;
inline void UpdateReply::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& UpdateReply::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:UpdateReply.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UpdateReply::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:UpdateReply.message)
}
inline std::string* UpdateReply::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:UpdateReply.message)
  return _s;
}
inline const std::string& UpdateReply::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void UpdateReply::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* UpdateReply::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* UpdateReply::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:UpdateReply.message)
  return _impl_.message_.Release();
}
inline void UpdateReply::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:UpdateReply.message)
}

// int32 errorCode = 3;
inline void UpdateReply::clear_errorcode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errorcode_ = 0;
}
inline ::int32_t UpdateReply::errorcode() const {
  // @@protoc_insertion_point(field_get:UpdateReply.errorCode)
  return _internal_errorcode();
}
inline void UpdateReply::set_errorcode(::int32_t value) {
  _internal_set_errorcode(value);
  // @@protoc_insertion_point(field_set:UpdateReply.errorCode)
}
inline ::int32_t UpdateReply::_internal_errorcode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errorcode_;
}
inline void UpdateReply::_internal_set_errorcode(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errorcode_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // training_2eproto_2epb_2eh
