// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: training.proto
// Protobuf C++ Version: 5.29.5

#include "training.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr UpdateReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{false},
        errorcode_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateReply::UpdateReply(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateReplyDefaultTypeInternal() {}
  union {
    UpdateReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateReplyDefaultTypeInternal _UpdateReply_default_instance_;

inline constexpr TrainingStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : statusmessage_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        istraining_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TrainingStatus::TrainingStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TrainingStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrainingStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrainingStatusDefaultTypeInternal() {}
  union {
    TrainingStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrainingStatusDefaultTypeInternal _TrainingStatus_default_instance_;

inline constexpr TrainingMetrics::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : currentloss_{0},
        currentiteration_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TrainingMetrics::TrainingMetrics(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TrainingMetricsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrainingMetricsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrainingMetricsDefaultTypeInternal() {}
  union {
    TrainingMetrics _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrainingMetricsDefaultTypeInternal _TrainingMetrics_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_training_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_training_2eproto = nullptr;
const ::uint32_t
    TableStruct_training_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::TrainingStatus, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::TrainingStatus, _impl_.istraining_),
        PROTOBUF_FIELD_OFFSET(::TrainingStatus, _impl_.statusmessage_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::TrainingMetrics, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::TrainingMetrics, _impl_.currentloss_),
        PROTOBUF_FIELD_OFFSET(::TrainingMetrics, _impl_.currentiteration_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::UpdateReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::UpdateReply, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::UpdateReply, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::UpdateReply, _impl_.errorcode_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::TrainingStatus)},
        {10, -1, -1, sizeof(::TrainingMetrics)},
        {20, -1, -1, sizeof(::UpdateReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_TrainingStatus_default_instance_._instance,
    &::_TrainingMetrics_default_instance_._instance,
    &::_UpdateReply_default_instance_._instance,
};
const char descriptor_table_protodef_training_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016training.proto\";\n\016TrainingStatus\022\022\n\nis"
    "Training\030\001 \001(\010\022\025\n\rstatusMessage\030\002 \001(\t\"@\n"
    "\017TrainingMetrics\022\023\n\013currentLoss\030\001 \001(\002\022\030\n"
    "\020currentIteration\030\002 \001(\002\"A\n\013UpdateReply\022\016"
    "\n\006status\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\021\n\terror"
    "Code\030\003 \001(\0052z\n\010Training\0225\n\024TrainingStatus"
    "Update\022\017.TrainingStatus\032\014.UpdateReply\0227\n"
    "\025TrainingMetricsUpdate\022\020.TrainingMetrics"
    "\032\014.UpdateReplyb\006proto3"
};
static ::absl::once_flag descriptor_table_training_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_training_2eproto = {
    false,
    false,
    342,
    descriptor_table_protodef_training_2eproto,
    "training.proto",
    &descriptor_table_training_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_training_2eproto::offsets,
    file_level_enum_descriptors_training_2eproto,
    file_level_service_descriptors_training_2eproto,
};
// ===================================================================

class TrainingStatus::_Internal {
 public:
};

TrainingStatus::TrainingStatus(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TrainingStatus)
}
inline PROTOBUF_NDEBUG_INLINE TrainingStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::TrainingStatus& from_msg)
      : statusmessage_(arena, from.statusmessage_),
        _cached_size_{0} {}

TrainingStatus::TrainingStatus(
    ::google::protobuf::Arena* arena,
    const TrainingStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TrainingStatus* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.istraining_ = from._impl_.istraining_;

  // @@protoc_insertion_point(copy_constructor:TrainingStatus)
}
inline PROTOBUF_NDEBUG_INLINE TrainingStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : statusmessage_(arena),
        _cached_size_{0} {}

inline void TrainingStatus::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.istraining_ = {};
}
TrainingStatus::~TrainingStatus() {
  // @@protoc_insertion_point(destructor:TrainingStatus)
  SharedDtor(*this);
}
inline void TrainingStatus::SharedDtor(MessageLite& self) {
  TrainingStatus& this_ = static_cast<TrainingStatus&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.statusmessage_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TrainingStatus::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TrainingStatus(arena);
}
constexpr auto TrainingStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TrainingStatus),
                                            alignof(TrainingStatus));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TrainingStatus::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TrainingStatus_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TrainingStatus::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TrainingStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TrainingStatus::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TrainingStatus>(), &TrainingStatus::ByteSizeLong,
            &TrainingStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TrainingStatus, _impl_._cached_size_),
        false,
    },
    &TrainingStatus::kDescriptorMethods,
    &descriptor_table_training_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TrainingStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 36, 2> TrainingStatus::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TrainingStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string statusMessage = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TrainingStatus, _impl_.statusmessage_)}},
    // bool isTraining = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TrainingStatus, _impl_.istraining_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(TrainingStatus, _impl_.istraining_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool isTraining = 1;
    {PROTOBUF_FIELD_OFFSET(TrainingStatus, _impl_.istraining_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string statusMessage = 2;
    {PROTOBUF_FIELD_OFFSET(TrainingStatus, _impl_.statusmessage_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\15\0\0\0\0\0"
    "TrainingStatus"
    "statusMessage"
  }},
};

PROTOBUF_NOINLINE void TrainingStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:TrainingStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.statusmessage_.ClearToEmpty();
  _impl_.istraining_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TrainingStatus::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TrainingStatus& this_ = static_cast<const TrainingStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TrainingStatus::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TrainingStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:TrainingStatus)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool isTraining = 1;
          if (this_._internal_istraining() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_istraining(), target);
          }

          // string statusMessage = 2;
          if (!this_._internal_statusmessage().empty()) {
            const std::string& _s = this_._internal_statusmessage();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "TrainingStatus.statusMessage");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:TrainingStatus)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TrainingStatus::ByteSizeLong(const MessageLite& base) {
          const TrainingStatus& this_ = static_cast<const TrainingStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TrainingStatus::ByteSizeLong() const {
          const TrainingStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:TrainingStatus)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string statusMessage = 2;
            if (!this_._internal_statusmessage().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_statusmessage());
            }
            // bool isTraining = 1;
            if (this_._internal_istraining() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TrainingStatus::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TrainingStatus*>(&to_msg);
  auto& from = static_cast<const TrainingStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TrainingStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_statusmessage().empty()) {
    _this->_internal_set_statusmessage(from._internal_statusmessage());
  }
  if (from._internal_istraining() != 0) {
    _this->_impl_.istraining_ = from._impl_.istraining_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TrainingStatus::CopyFrom(const TrainingStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TrainingStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TrainingStatus::InternalSwap(TrainingStatus* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.statusmessage_, &other->_impl_.statusmessage_, arena);
        swap(_impl_.istraining_, other->_impl_.istraining_);
}

::google::protobuf::Metadata TrainingStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class TrainingMetrics::_Internal {
 public:
};

TrainingMetrics::TrainingMetrics(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TrainingMetrics)
}
TrainingMetrics::TrainingMetrics(
    ::google::protobuf::Arena* arena, const TrainingMetrics& from)
    : TrainingMetrics(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE TrainingMetrics::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void TrainingMetrics::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, currentloss_),
           0,
           offsetof(Impl_, currentiteration_) -
               offsetof(Impl_, currentloss_) +
               sizeof(Impl_::currentiteration_));
}
TrainingMetrics::~TrainingMetrics() {
  // @@protoc_insertion_point(destructor:TrainingMetrics)
  SharedDtor(*this);
}
inline void TrainingMetrics::SharedDtor(MessageLite& self) {
  TrainingMetrics& this_ = static_cast<TrainingMetrics&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* TrainingMetrics::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TrainingMetrics(arena);
}
constexpr auto TrainingMetrics::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(TrainingMetrics),
                                            alignof(TrainingMetrics));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TrainingMetrics::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TrainingMetrics_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TrainingMetrics::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TrainingMetrics>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TrainingMetrics::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TrainingMetrics>(), &TrainingMetrics::ByteSizeLong,
            &TrainingMetrics::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TrainingMetrics, _impl_._cached_size_),
        false,
    },
    &TrainingMetrics::kDescriptorMethods,
    &descriptor_table_training_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TrainingMetrics::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> TrainingMetrics::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TrainingMetrics>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float currentIteration = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(TrainingMetrics, _impl_.currentiteration_)}},
    // float currentLoss = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(TrainingMetrics, _impl_.currentloss_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float currentLoss = 1;
    {PROTOBUF_FIELD_OFFSET(TrainingMetrics, _impl_.currentloss_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float currentIteration = 2;
    {PROTOBUF_FIELD_OFFSET(TrainingMetrics, _impl_.currentiteration_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void TrainingMetrics::Clear() {
// @@protoc_insertion_point(message_clear_start:TrainingMetrics)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.currentloss_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.currentiteration_) -
      reinterpret_cast<char*>(&_impl_.currentloss_)) + sizeof(_impl_.currentiteration_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TrainingMetrics::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TrainingMetrics& this_ = static_cast<const TrainingMetrics&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TrainingMetrics::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TrainingMetrics& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:TrainingMetrics)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float currentLoss = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_currentloss()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_currentloss(), target);
          }

          // float currentIteration = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_currentiteration()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_currentiteration(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:TrainingMetrics)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TrainingMetrics::ByteSizeLong(const MessageLite& base) {
          const TrainingMetrics& this_ = static_cast<const TrainingMetrics&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TrainingMetrics::ByteSizeLong() const {
          const TrainingMetrics& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:TrainingMetrics)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float currentLoss = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_currentloss()) != 0) {
              total_size += 5;
            }
            // float currentIteration = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_currentiteration()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TrainingMetrics::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TrainingMetrics*>(&to_msg);
  auto& from = static_cast<const TrainingMetrics&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TrainingMetrics)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_currentloss()) != 0) {
    _this->_impl_.currentloss_ = from._impl_.currentloss_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_currentiteration()) != 0) {
    _this->_impl_.currentiteration_ = from._impl_.currentiteration_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TrainingMetrics::CopyFrom(const TrainingMetrics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TrainingMetrics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TrainingMetrics::InternalSwap(TrainingMetrics* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TrainingMetrics, _impl_.currentiteration_)
      + sizeof(TrainingMetrics::_impl_.currentiteration_)
      - PROTOBUF_FIELD_OFFSET(TrainingMetrics, _impl_.currentloss_)>(
          reinterpret_cast<char*>(&_impl_.currentloss_),
          reinterpret_cast<char*>(&other->_impl_.currentloss_));
}

::google::protobuf::Metadata TrainingMetrics::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateReply::_Internal {
 public:
};

UpdateReply::UpdateReply(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:UpdateReply)
}
inline PROTOBUF_NDEBUG_INLINE UpdateReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::UpdateReply& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

UpdateReply::UpdateReply(
    ::google::protobuf::Arena* arena,
    const UpdateReply& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, status_),
           offsetof(Impl_, errorcode_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::errorcode_));

  // @@protoc_insertion_point(copy_constructor:UpdateReply)
}
inline PROTOBUF_NDEBUG_INLINE UpdateReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void UpdateReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, status_),
           0,
           offsetof(Impl_, errorcode_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::errorcode_));
}
UpdateReply::~UpdateReply() {
  // @@protoc_insertion_point(destructor:UpdateReply)
  SharedDtor(*this);
}
inline void UpdateReply::SharedDtor(MessageLite& self) {
  UpdateReply& this_ = static_cast<UpdateReply&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UpdateReply::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateReply(arena);
}
constexpr auto UpdateReply::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UpdateReply),
                                            alignof(UpdateReply));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateReply::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateReply_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateReply::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UpdateReply>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateReply::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UpdateReply>(), &UpdateReply::ByteSizeLong,
            &UpdateReply::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_._cached_size_),
        false,
    },
    &UpdateReply::kDescriptorMethods,
    &descriptor_table_training_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateReply::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 27, 2> UpdateReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::UpdateReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateReply, _impl_.status_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.status_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.message_)}},
    // int32 errorCode = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UpdateReply, _impl_.errorcode_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.errorcode_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool status = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 errorCode = 3;
    {PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.errorcode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\13\0\7\0\0\0\0\0"
    "UpdateReply"
    "message"
  }},
};

PROTOBUF_NOINLINE void UpdateReply::Clear() {
// @@protoc_insertion_point(message_clear_start:UpdateReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  ::memset(&_impl_.status_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.errorcode_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.errorcode_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateReply::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateReply& this_ = static_cast<const UpdateReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateReply::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:UpdateReply)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool status = 1;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_status(), target);
          }

          // string message = 2;
          if (!this_._internal_message().empty()) {
            const std::string& _s = this_._internal_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "UpdateReply.message");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 errorCode = 3;
          if (this_._internal_errorcode() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_errorcode(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:UpdateReply)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateReply::ByteSizeLong(const MessageLite& base) {
          const UpdateReply& this_ = static_cast<const UpdateReply&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateReply::ByteSizeLong() const {
          const UpdateReply& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:UpdateReply)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string message = 2;
            if (!this_._internal_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message());
            }
            // bool status = 1;
            if (this_._internal_status() != 0) {
              total_size += 2;
            }
            // int32 errorCode = 3;
            if (this_._internal_errorcode() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_errorcode());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateReply*>(&to_msg);
  auto& from = static_cast<const UpdateReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:UpdateReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  if (from._internal_errorcode() != 0) {
    _this->_impl_.errorcode_ = from._impl_.errorcode_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateReply::CopyFrom(const UpdateReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:UpdateReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateReply::InternalSwap(UpdateReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.errorcode_)
      + sizeof(UpdateReply::_impl_.errorcode_)
      - PROTOBUF_FIELD_OFFSET(UpdateReply, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::google::protobuf::Metadata UpdateReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_training_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
