# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dashboard_pb2 as dashboard__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dashboard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DashboardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBatchUpdate = channel.unary_unary(
                '/Dashboard/SendBatchUpdate',
                request_serializer=dashboard__pb2.BatchUpdate.SerializeToString,
                response_deserializer=dashboard__pb2.UpdateReply.FromString,
                _registered_method=True)
        self.SendLossUpdate = channel.unary_unary(
                '/Dashboard/SendLossUpdate',
                request_serializer=dashboard__pb2.LossUpdate.SerializeToString,
                response_deserializer=dashboard__pb2.UpdateReply.FromString,
                _registered_method=True)


class DashboardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendBatchUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLossUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DashboardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBatchUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBatchUpdate,
                    request_deserializer=dashboard__pb2.BatchUpdate.FromString,
                    response_serializer=dashboard__pb2.UpdateReply.SerializeToString,
            ),
            'SendLossUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLossUpdate,
                    request_deserializer=dashboard__pb2.LossUpdate.FromString,
                    response_serializer=dashboard__pb2.UpdateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Dashboard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Dashboard', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Dashboard(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendBatchUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Dashboard/SendBatchUpdate',
            dashboard__pb2.BatchUpdate.SerializeToString,
            dashboard__pb2.UpdateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLossUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Dashboard/SendLossUpdate',
            dashboard__pb2.LossUpdate.SerializeToString,
            dashboard__pb2.UpdateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
