# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dashboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61shboard.proto\"9\n\tImageData\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"c\n\x0b\x42\x61tchUpdate\x12\x1a\n\x06images\x18\x01 \x03(\x0b\x32\n.ImageData\x12\x13\n\x0bpredictions\x18\x02 \x03(\t\x12\x14\n\x0cgroundTruths\x18\x03 \x03(\t\x12\r\n\x05index\x18\x04 \x01(\x05\"2\n\nLossUpdate\x12\x11\n\tlossValue\x18\x01 \x01(\x02\x12\x11\n\titeration\x18\x02 \x01(\x05\"A\n\x0bUpdateReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\terrorCode\x18\x03 \x01(\x05\x32g\n\tDashboard\x12-\n\x0fSendBatchUpdate\x12\x0c.BatchUpdate\x1a\x0c.UpdateReply\x12+\n\x0eSendLossUpdate\x12\x0b.LossUpdate\x1a\x0c.UpdateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEDATA']._serialized_start=19
  _globals['_IMAGEDATA']._serialized_end=76
  _globals['_BATCHUPDATE']._serialized_start=78
  _globals['_BATCHUPDATE']._serialized_end=177
  _globals['_LOSSUPDATE']._serialized_start=179
  _globals['_LOSSUPDATE']._serialized_end=229
  _globals['_UPDATEREPLY']._serialized_start=231
  _globals['_UPDATEREPLY']._serialized_end=296
  _globals['_DASHBOARD']._serialized_start=298
  _globals['_DASHBOARD']._serialized_end=401
# @@protoc_insertion_point(module_scope)
