# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import training_pb2 as training__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in training_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainingStatusUpdate = channel.unary_unary(
                '/Training/TrainingStatusUpdate',
                request_serializer=training__pb2.TrainingStatus.SerializeToString,
                response_deserializer=training__pb2.TrainingUpdateReply.FromString,
                _registered_method=True)
        self.TrainingMetricsUpdate = channel.unary_unary(
                '/Training/TrainingMetricsUpdate',
                request_serializer=training__pb2.TrainingMetrics.SerializeToString,
                response_deserializer=training__pb2.TrainingUpdateReply.FromString,
                _registered_method=True)


class TrainingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrainingStatusUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainingMetricsUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainingStatusUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainingStatusUpdate,
                    request_deserializer=training__pb2.TrainingStatus.FromString,
                    response_serializer=training__pb2.TrainingUpdateReply.SerializeToString,
            ),
            'TrainingMetricsUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainingMetricsUpdate,
                    request_deserializer=training__pb2.TrainingMetrics.FromString,
                    response_serializer=training__pb2.TrainingUpdateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Training', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Training', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Training(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrainingStatusUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Training/TrainingStatusUpdate',
            training__pb2.TrainingStatus.SerializeToString,
            training__pb2.TrainingUpdateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainingMetricsUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Training/TrainingMetricsUpdate',
            training__pb2.TrainingMetrics.SerializeToString,
            training__pb2.TrainingUpdateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
