# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: training.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'training.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etraining.proto\"\x07\n\x05\x45mpty\"\x13\n\x05\x44\x65lay\x12\n\n\x02ms\x18\x01 \x01(\x05\";\n\x0eTrainingStatus\x12\x12\n\nisTraining\x18\x01 \x01(\x08\x12\x15\n\rstatusMessage\x18\x02 \x01(\t\"@\n\x0fTrainingMetrics\x12\x13\n\x0b\x63urrentLoss\x18\x01 \x01(\x02\x12\x18\n\x10\x63urrentIteration\x18\x02 \x01(\x02\"I\n\x13TrainingUpdateReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\terrorCode\x18\x03 \x01(\x05\x32\x8a\x01\n\x08Training\x12=\n\x14TrainingStatusUpdate\x12\x0f.TrainingStatus\x1a\x14.TrainingUpdateReply\x12?\n\x15TrainingMetricsUpdate\x12\x10.TrainingMetrics\x1a\x14.TrainingUpdateReply2`\n\x0fTrainingControl\x12\x17\n\x05Pause\x12\x06.Empty\x1a\x06.Empty\x12\x18\n\x06Resume\x12\x06.Empty\x1a\x06.Empty\x12\x1a\n\x08SetDelay\x12\x06.Delay\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'training_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_DELAY']._serialized_start=27
  _globals['_DELAY']._serialized_end=46
  _globals['_TRAININGSTATUS']._serialized_start=48
  _globals['_TRAININGSTATUS']._serialized_end=107
  _globals['_TRAININGMETRICS']._serialized_start=109
  _globals['_TRAININGMETRICS']._serialized_end=173
  _globals['_TRAININGUPDATEREPLY']._serialized_start=175
  _globals['_TRAININGUPDATEREPLY']._serialized_end=248
  _globals['_TRAINING']._serialized_start=251
  _globals['_TRAINING']._serialized_end=389
  _globals['_TRAININGCONTROL']._serialized_start=391
  _globals['_TRAININGCONTROL']._serialized_end=487
# @@protoc_insertion_point(module_scope)
