# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: training.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'training.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etraining.proto\";\n\x0eTrainingStatus\x12\x12\n\nisTraining\x18\x01 \x01(\x08\x12\x15\n\rstatusMessage\x18\x02 \x01(\t\"@\n\x0fTrainingMetrics\x12\x13\n\x0b\x63urrentLoss\x18\x01 \x01(\x02\x12\x18\n\x10\x63urrentIteration\x18\x02 \x01(\x02\"I\n\x13TrainingUpdateReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\terrorCode\x18\x03 \x01(\x05\x32\x8a\x01\n\x08Training\x12=\n\x14TrainingStatusUpdate\x12\x0f.TrainingStatus\x1a\x14.TrainingUpdateReply\x12?\n\x15TrainingMetricsUpdate\x12\x10.TrainingMetrics\x1a\x14.TrainingUpdateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'training_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAININGSTATUS']._serialized_start=18
  _globals['_TRAININGSTATUS']._serialized_end=77
  _globals['_TRAININGMETRICS']._serialized_start=79
  _globals['_TRAININGMETRICS']._serialized_end=143
  _globals['_TRAININGUPDATEREPLY']._serialized_start=145
  _globals['_TRAININGUPDATEREPLY']._serialized_end=218
  _globals['_TRAINING']._serialized_start=221
  _globals['_TRAINING']._serialized_end=359
# @@protoc_insertion_point(module_scope)
